# Site settings
title: Ritesh Jain
email: contact@riteshjn.com
baseurl: ""
url: "https://riteshjn.com"


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "PhD scholar/Research Assistant"
excerpt_separator: "<!--more-->"

#Gems


plugins:
  - jekyll-sitemap
  - jekyll-email-protect

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
